{% set version = "1.0.1" %}

package:
  name: varys
  version: {{ version }}

source:
  url: https://github.com/CLIMB-TRE/varys/archive/refs/tags/{{ version }}.tar.gz
  sha256: 296f9e1621551351f193d5608daebc5076d28415add65c398a16ffc902cacb6f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}
    - pika >=1.3.0

test:
  imports:
    - varys
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check


about:
  home: https://github.com/CLIMB-TRE/varys
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: 'varys: a RabbitMQ python client, master of whispers for CLIMB-TRE'
  license_family: GPL

extra:
  recipe-maintainers:
    - BioWilko
