{% set version = "1.1.1" %}

package:
  name: varys
  version: {{ version }}

source:
  url: https://github.com/CLIMB-TRE/varys/archive/refs/tags/{{ version }}.tar.gz
  sha256: 93b62d9ceb05085501dc1aabcb689a7a058a43ba379132ee79a8bf998932ce6b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - pika >=1.3.0

test:
  imports:
    - varys
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check


about:
  home: https://github.com/CLIMB-TRE/varys
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: 'varys: a RabbitMQ python client, master of whispers for CLIMB-TRE'
  license_family: GPL

extra:
  recipe-maintainers:
    - BioWilko
