{% set version = "1.1.0" %}

package:
  name: varys
  version: {{ version }}

source:
  url: https://github.com/CLIMB-TRE/varys/archive/refs/tags/{{ version }}.tar.gz
  sha256: bfa1dd2f5de0dc982f0683e63609d2daabb70b9284512b80cb88cc8aa3740b00

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}
    - pika >=1.3.0

test:
  imports:
    - varys
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check


about:
  home: https://github.com/CLIMB-TRE/varys
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: 'varys: a RabbitMQ python client, master of whispers for CLIMB-TRE'
  license_family: GPL

extra:
  recipe-maintainers:
    - BioWilko
